//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BusinessEntities : DbContext
    {
        public BusinessEntities()
            : base("name=BusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRSN> PRSNs { get; set; }
    
        public virtual ObjectResult<SelectAllCities_Result> SelectAllCities()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllCities_Result>("SelectAllCities");
        }
    
        public virtual ObjectResult<SelectCity_Result> SelectCity(string city)
        {
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCity_Result>("SelectCity", cityParameter);
        }
    }
}
